# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=None)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('1e', '여름'), ('2e', '겨울')], default='1', max_length=4)),
                ('code', models.CharField(max_length=6)),
                ('division', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=4)),
                ('capacity', models.IntegerField()),
                ('university', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('grade', models.IntegerField(null=True)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='7', max_length=1)),
                ('time', models.PositiveIntegerField(default=0)),
                ('place', models.CharField(max_length=30)),
                ('class_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='classrating.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classrating.Professor'),
        ),
    ]
