# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=0)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('1e', '여름'), ('2e', '겨울')], default='1', max_length=4)),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('year', 'semester', 'code', 'division')]),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('class_to', 'day', 'place')]),
        ),
    ]
