# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrating', '0002_auto_20170820_2332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('class_to', 'day', 'time')]),
        ),
    ]
