# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrating', '0004_auto_20170829_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
